package lesson6.dao;

import java.util.List;
import lesson6.model.Categories;
import lesson6.model.CategoriesExample;
import org.apache.ibatis.annotations.Param;

public interface CategoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    long countByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int deleteByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int insert(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int insertSelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    List<Categories> selectByExample(CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    Categories selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int updateByExampleSelective(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int updateByExample(@Param("record") Categories record, @Param("example") CategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int updateByPrimaryKeySelective(Categories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CATEGORIES
     *
     * @mbg.generated Wed Dec 22 17:16:32 GMT+04:00 2021
     */
    int updateByPrimaryKey(Categories record);
}